export { default as Navbar} from './navbar/Navbar'
export { default as Layout} from './layout/Layout'
export { default as Footer} from './footer/Footer'
export { default as Home} from './home/Home'
export { default as Bundle} from './Bundle/Bundle'
export { default as Cart} from './Cart/Cart'
export { default as Menu} from './Menu/Menu'
export {default as Travaux} from './travaux/Travaux'
export {default as DiscountLayer} from './DiscountLayer/DiscountLayer'